{% set name = "socketify" %}
{% set version = "0.0.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/cirospaciari/socketify.py/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 55172159512b3805094bd50cdb542261e20ea1e4e23daf022c8d83ca3382c8ee
    patches:
      - fix_native_makefile.diff

  - url: https://github.com/cirospaciari/uWebSockets/archive/f33291d10a2051ba0f10c18761c030fb00390fdf.tar.gz
    sha256: a7e7e2c11287d857ab0a25300605adbee6932ecd12ac60eea5596944666492f7
    folder: src/socketify/uWebSockets

  - url: https://github.com/cirospaciari/uSockets/archive/0b95ddfa4971a8e90d2f5f9e33b5317985dceaa1.tar.gz
    sha256: c6c1cab5ac2d679f961e76f09713526d72227b0386e70a23a90e5123cbfe2880
    folder: src/socketify/uWebSockets/uSockets

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - libuv
    - openssl
    - zlib
    - python
    - cffi >=1.0
    - setuptools >=58.1
    - pip
  run:
    - python
    - cffi >=1.0
    - setuptools >=58.1.0

test:
  imports:
    - socketify
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cirospaciari/socketify.py
  summary: Bringing WebSockets, Http/Https High Performance servers for PyPy3 and Python3
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE
    - src/socketify/uWebSockets/LICENSE
    - src/socketify/uWebSockets/uSockets/LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
